export const QUIZ_MODES = ['arcade', 'coach'];

export const QUIZ_DIFFICULTIES = ['foundation', 'intermediate', 'advanced'];

export const QUIZ_CATEGORIES = [
  { id: 'agile-principles', label: 'Agile principles' },
  { id: 'scrum', label: 'Scrum' },
  { id: 'kanban-flow', label: 'Kanban and flow' },
  { id: 'delivery-programme', label: 'Delivery and programme management' },
  { id: 'stakeholders-risk', label: 'Stakeholders, dependencies and risk' },
  { id: 'facilitation-coaching', label: 'Facilitation, coaching and team health' },
];

const agileManifesto = (section = 'Manifesto values') => ({
  type: 'primary',
  title: 'Manifesto for Agile Software Development',
  section,
  url: 'https://agilemanifesto.org/',
});

const agilePrinciples = (section = 'Principles behind the Agile Manifesto') => ({
  type: 'primary',
  title: 'Principles behind the Agile Manifesto',
  section,
  url: 'https://agilemanifesto.org/principles.html',
});

const scrumGuide = (section) => ({
  type: 'primary',
  title: 'Scrum Guide 2020',
  section,
  url: 'https://scrumguides.org/scrum-guide.html',
});

const kanbanGuide = (section) => ({
  type: 'primary',
  title: 'Kanban Guide May 2025',
  section,
  url: 'https://kanbanguides.org/the-kanban-guide/',
});

const choices = (a, b, c, d) => [
  { id: 'a', text: a },
  { id: 'b', text: b },
  { id: 'c', text: c },
  { id: 'd', text: d },
];

export const QUIZ_QUESTIONS = [
  {
    id: 'agile-principles-001',
    modes: ['arcade', 'coach'],
    category: 'agile-principles',
    difficulty: 'foundation',
    prompt: 'Which Agile Manifesto value best supports a team choosing a direct conversation over a long handoff document?',
    choices: choices('Working software over comprehensive documentation', 'Individuals and interactions over processes and tools', 'Customer collaboration over contract negotiation', 'Responding to change over following a plan'),
    correctChoiceId: 'b',
    explanation: 'The value is individuals and interactions over processes and tools. Documentation can help, but Agile gives more weight to effective collaboration between people.',
    whyItMatters: 'Delivery roles often improve flow fastest by reducing handoff friction and creating clearer shared understanding.',
    reference: agileManifesto('Values'),
    tags: ['manifesto-values', 'collaboration'],
  },
  {
    id: 'agile-principles-002',
    modes: ['arcade', 'coach'],
    category: 'agile-principles',
    difficulty: 'foundation',
    prompt: 'A sponsor asks how progress should primarily be demonstrated in an Agile delivery review. What is the strongest answer?',
    choices: choices('A completed status report', 'A detailed milestone Gantt chart', 'Working product or service evidence', 'A list of meetings held'),
    correctChoiceId: 'c',
    explanation: 'One Agile principle says working software is the primary measure of progress. In broader delivery contexts, the same idea means showing usable value, not just activity.',
    whyItMatters: 'Progress evidence keeps conversations grounded in outcomes and reduces false confidence from activity tracking alone.',
    reference: agilePrinciples('Working software as progress'),
    tags: ['progress', 'value'],
  },
  {
    id: 'agile-principles-003',
    modes: ['arcade', 'coach'],
    category: 'agile-principles',
    difficulty: 'intermediate',
    prompt: 'Halfway through delivery, customer evidence shows a planned feature is less valuable than a new request. What is the best Agile response?',
    scenarioContext: 'The change is late, but it is backed by real customer learning and can be traded against lower-value scope.',
    choices: choices('Reject the change because the plan was approved', 'Accept every new idea and keep all existing scope', 'Use the learning to renegotiate scope and maximise value', 'Pause delivery until all stakeholders agree on a final fixed scope'),
    correctChoiceId: 'c',
    explanation: 'Agile welcomes changing requirements when the change improves customer advantage, but that does not mean adding unlimited work. The best response is value-based tradeoff.',
    whyItMatters: 'Agility is not churn. It is disciplined adaptation when new information changes the best economic choice.',
    reference: agilePrinciples('Welcome changing requirements'),
    tags: ['change', 'scope-tradeoff'],
  },
  {
    id: 'agile-principles-004',
    modes: ['arcade', 'coach'],
    category: 'agile-principles',
    difficulty: 'intermediate',
    prompt: 'A delivery manager sees a team planning three months of detail before validating any user outcome. Which coaching point is strongest?',
    scenarioContext: 'The team has enough uncertainty that early feedback could change the solution.',
    choices: choices('Plan every dependency before the first release', 'Deliver smaller slices frequently to learn sooner', 'Skip planning and start all known work at once', 'Use only technical tasks until stakeholders are ready'),
    correctChoiceId: 'b',
    explanation: 'Agile principles favour frequent delivery on shorter timescales. Smaller slices create earlier feedback and reduce the cost of being wrong.',
    whyItMatters: 'Programme plans are healthier when they expose assumptions early instead of hiding uncertainty behind detailed schedules.',
    reference: agilePrinciples('Deliver working software frequently'),
    tags: ['incremental-delivery', 'feedback'],
  },
  {
    id: 'agile-principles-005',
    modes: ['arcade', 'coach'],
    category: 'agile-principles',
    difficulty: 'intermediate',
    prompt: 'A team says it is too busy to improve build quality because feature demand is high. What Agile principle should guide the conversation?',
    choices: choices('Technical excellence and good design enhance agility', 'Face-to-face communication replaces engineering discipline', 'Late changes should always be rejected', 'Documentation should be removed from the process'),
    correctChoiceId: 'a',
    explanation: 'Continuous attention to technical excellence and good design enhances agility. Quality shortcuts often reduce future adaptability.',
    whyItMatters: 'Technical programme and delivery leaders need to protect quality because hidden quality debt becomes delivery risk.',
    reference: agilePrinciples('Technical excellence'),
    tags: ['quality', 'technical-excellence'],
  },
  {
    id: 'agile-principles-006',
    modes: ['arcade', 'coach'],
    category: 'agile-principles',
    difficulty: 'advanced',
    prompt: 'A portfolio board wants every team to commit to fixed annual scope, but teams work in uncertain problem spaces. What is the best Agile-aligned reframing?',
    scenarioContext: 'Executives still need governance, but fixed scope commitments are repeatedly wrong.',
    choices: choices('Ask teams to make stronger commitments to the same scope', 'Replace governance with team autonomy and no reporting', 'Govern by outcomes, short feedback loops and explicit tradeoffs', 'Only fund projects after all requirements are stable'),
    correctChoiceId: 'c',
    explanation: 'Agile values responding to change and frequent delivery of value. Governance can still exist, but it should steer outcomes and tradeoffs rather than pretending uncertain scope is fixed.',
    whyItMatters: 'Agile programme management should make uncertainty visible without abandoning accountability.',
    reference: agileManifesto('Responding to change over following a plan'),
    tags: ['governance', 'portfolio'],
  },
  {
    id: 'scrum-001',
    modes: ['arcade', 'coach'],
    category: 'scrum',
    difficulty: 'foundation',
    prompt: 'Which accountabilities are defined within a Scrum Team in the Scrum Guide 2020?',
    choices: choices('Product Owner, Scrum Master and Developers', 'Project Manager, Business Analyst and Test Lead', 'Product Manager, Delivery Manager and Engineers', 'Sponsor, Scrum Master and Technical Lead'),
    correctChoiceId: 'a',
    explanation: 'Scrum defines three specific accountabilities in the Scrum Team: Product Owner, Scrum Master and Developers.',
    whyItMatters: 'Using current Scrum terminology avoids importing command-and-control roles into the framework by accident.',
    reference: scrumGuide('Scrum Team'),
    tags: ['scrum-team', 'accountabilities'],
  },
  {
    id: 'scrum-002',
    modes: ['arcade', 'coach'],
    category: 'scrum',
    difficulty: 'foundation',
    prompt: 'Who is accountable for ordering Product Backlog items in Scrum?',
    choices: choices('The Developers', 'The Scrum Master', 'The Product Owner', 'The stakeholder committee'),
    correctChoiceId: 'c',
    explanation: 'The Product Owner is accountable for effective Product Backlog management, including ordering Product Backlog items.',
    whyItMatters: 'Clear accountability prevents priority decisions from becoming hidden negotiations across multiple unofficial owners.',
    reference: scrumGuide('Product Owner'),
    tags: ['product-backlog', 'product-owner'],
  },
  {
    id: 'scrum-003',
    modes: ['arcade', 'coach'],
    category: 'scrum',
    difficulty: 'intermediate',
    prompt: 'During a Sprint, new information suggests the selected work is more complex than expected. What can happen without breaking Scrum?',
    choices: choices('The Sprint Goal must never be discussed again', 'Scope may be clarified and renegotiated with the Product Owner as more is learned', 'The Scrum Master assigns overtime to protect every original item', 'The Sprint Review becomes the release approval gate'),
    correctChoiceId: 'b',
    explanation: 'The Scrum Guide says scope may be clarified and renegotiated with the Product Owner as more is learned, provided the Sprint Goal is not endangered.',
    whyItMatters: 'This distinction protects focus while allowing empirical adaptation inside the Sprint.',
    reference: scrumGuide('The Sprint'),
    tags: ['sprint-goal', 'scope'],
  },
  {
    id: 'scrum-004',
    modes: ['arcade', 'coach'],
    category: 'scrum',
    difficulty: 'intermediate',
    prompt: 'A Scrum Team treats Sprint Review as a slide presentation where stakeholders silently approve or reject work. What is the best correction?',
    scenarioContext: 'Stakeholders need to inspect real progress and influence what happens next.',
    choices: choices('Keep it as a sign-off gate to protect governance', 'Turn it into a working session to inspect outcomes and adapt the Product Backlog', 'Cancel Sprint Review if the Increment is not ready to release', 'Move all stakeholder feedback to the Sprint Retrospective'),
    correctChoiceId: 'b',
    explanation: 'Sprint Review is a working session where the Scrum Team and stakeholders inspect the outcome and collaborate on what to do next. It should not be reduced to a presentation.',
    whyItMatters: 'Good reviews improve product direction and reduce late stakeholder surprises.',
    reference: scrumGuide('Sprint Review'),
    tags: ['sprint-review', 'stakeholders'],
  },
  {
    id: 'scrum-005',
    modes: ['arcade', 'coach'],
    category: 'scrum',
    difficulty: 'intermediate',
    prompt: 'The Daily Scrum has become a status meeting for a manager. Which change best fits the Scrum Guide?',
    choices: choices('Developers inspect progress toward the Sprint Goal and adapt the plan for the next day', 'The Product Owner collects estimates from every Developer', 'The Scrum Master assigns tasks by priority order', 'Stakeholders approve changes to the Sprint Backlog'),
    correctChoiceId: 'a',
    explanation: 'The Daily Scrum is for Developers to inspect progress toward the Sprint Goal and adapt the Sprint Backlog as necessary.',
    whyItMatters: 'A useful Daily Scrum strengthens self-management instead of creating a reporting queue.',
    reference: scrumGuide('Daily Scrum'),
    tags: ['daily-scrum', 'self-management'],
  },
  {
    id: 'scrum-006',
    modes: ['arcade', 'coach'],
    category: 'scrum',
    difficulty: 'advanced',
    prompt: 'Two Scrum Teams work on one product and disagree on what Done means. What is the best Scrum-aligned response?',
    scenarioContext: 'Both teams ship into the same product and stakeholders need transparency about releasable quality.',
    choices: choices('Let each team keep a private Definition of Done', 'Ask the Scrum Masters to approve exceptions after each Sprint', 'Mutually define and comply with the same Definition of Done', 'Remove the Definition of Done until quality improves'),
    correctChoiceId: 'c',
    explanation: 'When multiple Scrum Teams work together on a product, they must mutually define and comply with the same Definition of Done.',
    whyItMatters: 'A shared Definition of Done protects transparency when multiple teams contribute to one product increment.',
    reference: scrumGuide('Definition of Done'),
    tags: ['definition-of-done', 'multi-team'],
  },
  {
    id: 'kanban-flow-001',
    modes: ['arcade', 'coach'],
    category: 'kanban-flow',
    difficulty: 'foundation',
    prompt: 'According to the Kanban Guide May 2025, Kanban is a strategy for optimizing what?',
    choices: choices('The number of ceremonies in a delivery process', 'The flow of value through a process', 'The accuracy of individual utilization targets', 'The completeness of upfront requirements'),
    correctChoiceId: 'b',
    explanation: 'The Kanban Guide defines Kanban as a strategy for optimizing the flow of value through a process.',
    whyItMatters: 'Flow language keeps improvement work focused on value movement rather than local activity metrics.',
    reference: kanbanGuide('Definition of Kanban'),
    tags: ['kanban-definition', 'flow'],
  },
  {
    id: 'kanban-flow-002',
    modes: ['arcade', 'coach'],
    category: 'kanban-flow',
    difficulty: 'foundation',
    prompt: 'Which set best matches the three Kanban practices in the Kanban Guide May 2025?',
    choices: choices('Plan, estimate and assign', 'Define and visualize workflow, actively manage items, improve workflow', 'Sprint, review and retrospect', 'Prioritize, approve and report'),
    correctChoiceId: 'b',
    explanation: 'The three Kanban practices are defining and visualizing a workflow, actively managing items in a workflow, and improving a workflow.',
    whyItMatters: 'Kanban is more than a board. The practices connect visualization, active management and improvement.',
    reference: kanbanGuide('Kanban Practices'),
    tags: ['kanban-practices'],
  },
  {
    id: 'kanban-flow-003',
    modes: ['arcade', 'coach'],
    category: 'kanban-flow',
    difficulty: 'intermediate',
    prompt: 'A team starts all urgent requests immediately and now everything waits. What Kanban coaching response is strongest?',
    scenarioContext: 'The team has visible queues, blocked items and frequent context switching.',
    choices: choices('Increase individual utilization targets', 'Explicitly control WIP and start new work only when capacity is available', 'Hide blocked work until it is ready to finish', 'Add a daily status meeting but keep all work in progress'),
    correctChoiceId: 'b',
    explanation: 'Kanban system members must explicitly control work in progress. WIP control supports pull, focus and better flow.',
    whyItMatters: 'Delivery leaders often improve predictability by limiting started work, not by pushing more work into the system.',
    reference: kanbanGuide('Actively Managing Items in a Workflow'),
    tags: ['wip', 'pull-system'],
  },
  {
    id: 'kanban-flow-004',
    modes: ['arcade', 'coach'],
    category: 'kanban-flow',
    difficulty: 'intermediate',
    prompt: 'Which items are part of a minimum Definition of Workflow in the Kanban Guide May 2025?',
    choices: choices('Work item definition, workflow states, WIP control, explicit policies and an SLE', 'Sprint Goal, Product Goal, Increment and Definition of Done', 'Budget owner, steering committee, RAID log and change board', 'Team charter, roadmap, OKRs and release calendar only'),
    correctChoiceId: 'a',
    explanation: 'The guide lists minimum Definition of Workflow elements including work items, start/finish points, workflow states, WIP control, explicit policies and a service level expectation.',
    whyItMatters: 'A Definition of Workflow makes flow policies inspectable instead of relying on tribal knowledge.',
    reference: kanbanGuide('Defining and Visualizing the Workflow'),
    tags: ['definition-of-workflow', 'policies'],
  },
  {
    id: 'kanban-flow-005',
    modes: ['arcade', 'coach'],
    category: 'kanban-flow',
    difficulty: 'intermediate',
    prompt: 'A stakeholder asks for a delivery forecast. The team has historical cycle-time data. What is the strongest Kanban-informed response?',
    choices: choices('Promise the earliest possible date to create urgency', 'Use historical flow data and communicate the forecast with uncertainty', 'Report only story points completed last sprint', 'Avoid forecasts because Agile teams never forecast'),
    correctChoiceId: 'b',
    explanation: 'Kanban uses flow metrics and service level expectations to reason about predictability within uncertainty. Forecasts should be evidence based, not guarantees.',
    whyItMatters: 'Responsible delivery forecasting is transparent about uncertainty while still helping stakeholders make decisions.',
    reference: kanbanGuide('Flow Metrics'),
    tags: ['forecasting', 'service-level-expectation'],
  },
  {
    id: 'kanban-flow-006',
    modes: ['arcade', 'coach'],
    category: 'kanban-flow',
    difficulty: 'advanced',
    prompt: 'A programme board wants to improve predictability but only measures whether every person is fully allocated. What should an Agile delivery lead challenge?',
    scenarioContext: 'Queues are growing and handoffs are slow, but utilization looks high.',
    choices: choices('High utilization is always the best flow metric', 'Local utilization can hide queues, aging work and poor flow of value', 'Flow metrics should replace all stakeholder conversations', 'The team should remove WIP controls to increase throughput'),
    correctChoiceId: 'b',
    explanation: 'Kanban focuses on flow of value and balancing effectiveness, efficiency and predictability. Local utilization can work against system flow.',
    whyItMatters: 'Programme systems can look busy while value delivery slows; flow metrics reveal that problem earlier.',
    reference: kanbanGuide('Why Use Kanban?'),
    tags: ['flow-metrics', 'utilization'],
  },
  {
    id: 'delivery-programme-001',
    modes: ['arcade', 'coach'],
    category: 'delivery-programme',
    difficulty: 'foundation',
    prompt: 'A delivery manager inherits a roadmap with many outputs but no clear outcomes. What is the best first move?',
    choices: choices('Ask teams to estimate every output in more detail', 'Clarify the outcomes and value signals the roadmap is meant to change', 'Cancel all planned work until a new tool is selected', 'Move every item into the next sprint to create momentum'),
    correctChoiceId: 'b',
    explanation: 'The strongest response is to clarify outcomes and value signals before optimizing delivery of outputs. Practical delivery decisions need a target.',
    whyItMatters: 'Outcome clarity helps teams make tradeoffs when scope, time and dependencies compete.',
    tags: ['outcomes', 'roadmap'],
  },
  {
    id: 'delivery-programme-002',
    modes: ['arcade', 'coach'],
    category: 'delivery-programme',
    difficulty: 'foundation',
    prompt: 'Which delivery signal is most likely to reveal risk early in an Agile programme?',
    choices: choices('How many meetings were held', 'Whether teams have visible integrated increments or demonstrable slices', 'Whether every task is assigned to a named person', 'How many pages are in the governance pack'),
    correctChoiceId: 'b',
    explanation: 'Visible integrated increments or demonstrable slices show whether value and integration assumptions are actually working.',
    whyItMatters: 'Programme risk often hides at integration points; demonstrable slices expose it sooner than reports alone.',
    tags: ['programme-risk', 'integration'],
  },
  {
    id: 'delivery-programme-003',
    modes: ['arcade', 'coach'],
    category: 'delivery-programme',
    difficulty: 'intermediate',
    prompt: 'A technical programme has three teams blocked by the same platform dependency. What is the best TPM-style response?',
    scenarioContext: 'Each team is escalating separately and dates are starting to diverge.',
    choices: choices('Ask each team to solve the dependency independently', 'Create one visible dependency plan with owner, decision path, sequencing and risk options', 'Ignore the dependency until a sprint review exposes it', 'Move the platform work to the lowest-priority backlog'),
    correctChoiceId: 'b',
    explanation: 'The best response is to make the shared dependency explicit, align ownership and decision paths, and sequence work around real constraints.',
    whyItMatters: 'Technical programme management adds value by reducing cross-team ambiguity and making dependency risk manageable.',
    tags: ['dependencies', 'tpm'],
  },
  {
    id: 'delivery-programme-004',
    modes: ['arcade', 'coach'],
    category: 'delivery-programme',
    difficulty: 'intermediate',
    prompt: 'A programme milestone is at risk, but teams can still deliver a smaller valuable slice. What is the best recommendation?',
    choices: choices('Hide the risk until the milestone date', 'Discuss scope options and protect the most valuable coherent slice', 'Force every team to maintain original scope by adding overtime', 'Stop all discovery because delivery has started'),
    correctChoiceId: 'b',
    explanation: 'Protecting a coherent valuable slice and discussing tradeoffs early is stronger than hiding risk or preserving all scope regardless of value.',
    whyItMatters: 'Agile programme leadership should keep value, transparency and sustainable delivery in the same conversation.',
    tags: ['scope-tradeoff', 'milestones'],
  },
  {
    id: 'delivery-programme-005',
    modes: ['arcade', 'coach'],
    category: 'delivery-programme',
    difficulty: 'intermediate',
    prompt: 'An Agile Programme Manager sees each team improving locally, but end-to-end lead time is worsening. What should they inspect?',
    choices: choices('Only each individual team velocity', 'Cross-team flow, queues, handoffs and integration delays', 'Whether more status meetings can be added', 'The number of Jira fields completed'),
    correctChoiceId: 'b',
    explanation: 'When local optimization conflicts with end-to-end outcomes, inspect the whole flow: queues, handoffs, dependencies and integration delays.',
    whyItMatters: 'Programme delivery lives in the spaces between teams as much as inside individual team boards.',
    tags: ['end-to-end-flow', 'local-optimization'],
  },
  {
    id: 'delivery-programme-006',
    modes: ['arcade', 'coach'],
    category: 'delivery-programme',
    difficulty: 'advanced',
    prompt: 'A steering group wants a red/amber/green status but avoids discussing decisions needed to unblock delivery. What should the delivery lead do?',
    scenarioContext: 'The status pack is polished, but key decisions are repeatedly deferred.',
    choices: choices('Keep status high-level to avoid conflict', 'Frame the meeting around decisions, tradeoffs and consequences rather than colour alone', 'Remove risks from the report until they are certain', 'Ask teams to absorb the impact silently'),
    correctChoiceId: 'b',
    explanation: 'RAG status is useful only if it drives decisions. The stronger move is to surface tradeoffs, consequences and the decisions needed now.',
    whyItMatters: 'Governance should help delivery systems learn and decide, not just label them.',
    tags: ['governance', 'decision-making'],
  },
  {
    id: 'stakeholders-risk-001',
    modes: ['arcade', 'coach'],
    category: 'stakeholders-risk',
    difficulty: 'foundation',
    prompt: 'A stakeholder is affected by an outcome but is not funding the work. Should they still be considered in delivery planning?',
    choices: choices('No, only funders count as stakeholders', 'Yes, affected groups can be stakeholders even if they do not fund the work', 'Only if they attend every ceremony', 'Only after the release is complete'),
    correctChoiceId: 'b',
    explanation: 'In practical delivery and Kanban language, stakeholders include entities interested in or affected by outcomes, not only funders.',
    whyItMatters: 'Missing affected groups creates adoption, risk and value problems late in delivery.',
    reference: kanbanGuide('Conventions Used'),
    tags: ['stakeholders', 'impact'],
  },
  {
    id: 'stakeholders-risk-002',
    modes: ['arcade', 'coach'],
    category: 'stakeholders-risk',
    difficulty: 'foundation',
    prompt: 'A risk is uncertain but could materially harm delivery if it happens. What is the strongest Agile delivery response?',
    choices: choices('Ignore it until it becomes an issue', 'Make it visible, discuss options and decide the next risk-reducing action', 'Add it to a private list and avoid stakeholder concern', 'Assume the team will solve it without support'),
    correctChoiceId: 'b',
    explanation: 'Good Agile delivery makes uncertainty visible and turns it into learning or mitigation actions. Waiting until risk becomes an issue removes options.',
    whyItMatters: 'Risk conversations are most useful while decisions can still change the outcome.',
    tags: ['risk', 'transparency'],
  },
  {
    id: 'stakeholders-risk-003',
    modes: ['arcade', 'coach'],
    category: 'stakeholders-risk',
    difficulty: 'intermediate',
    prompt: 'Two senior stakeholders want conflicting priorities in the next increment. What should the delivery lead encourage?',
    scenarioContext: 'The team cannot do both without delaying a regulatory commitment.',
    choices: choices('Let the loudest stakeholder decide in the meeting', 'Make the tradeoff explicit and route the priority decision through the accountable product or governance path', 'Split the team and attempt both without changing dates', 'Ask Developers to choose silently to avoid conflict'),
    correctChoiceId: 'b',
    explanation: 'The best response is transparent tradeoff and accountable decision-making. Hidden priority conflict becomes delivery risk.',
    whyItMatters: 'Delivery leaders should make conflicting demand visible without pretending capacity is infinite.',
    tags: ['prioritization', 'tradeoffs'],
  },
  {
    id: 'stakeholders-risk-004',
    modes: ['arcade', 'coach'],
    category: 'stakeholders-risk',
    difficulty: 'intermediate',
    prompt: 'A dependency owner repeatedly misses promised dates. What is the best next step?',
    choices: choices('Keep the original plan unchanged to maintain confidence', 'Expose the dependency risk, agree recovery options and adjust plans based on evidence', 'Remove all mention of the dependency from team boards', 'Blame the dependent team for poor velocity'),
    correctChoiceId: 'b',
    explanation: 'A repeated dependency miss should trigger transparent risk management, recovery options and evidence-based replanning.',
    whyItMatters: 'Dependency risk improves when ownership, options and consequences are explicit.',
    tags: ['dependencies', 'risk-management'],
  },
  {
    id: 'stakeholders-risk-005',
    modes: ['arcade', 'coach'],
    category: 'stakeholders-risk',
    difficulty: 'intermediate',
    prompt: 'A stakeholder asks for a precise delivery date for work that has high uncertainty and little historical data. What is the strongest answer?',
    choices: choices('Give a precise date anyway to show confidence', 'Explain the uncertainty, share assumptions, and propose a plan to reduce uncertainty quickly', 'Refuse to discuss dates because Agile has no dates', 'Commit the team to working weekends if needed'),
    correctChoiceId: 'b',
    explanation: 'The best response is transparent uncertainty with assumptions and a learning plan. This supports decision-making without pretending certainty exists.',
    whyItMatters: 'Trust grows when forecasts are honest and paired with actions that improve predictability.',
    tags: ['forecasting', 'uncertainty'],
  },
  {
    id: 'stakeholders-risk-006',
    modes: ['arcade', 'coach'],
    category: 'stakeholders-risk',
    difficulty: 'advanced',
    prompt: 'A major compliance dependency is discovered late. The Product Owner wants to keep the Sprint Goal unchanged and absorb the work quietly. What is the strongest response?',
    scenarioContext: 'The compliance work could change scope and release risk for the current Sprint.',
    choices: choices('Absorb it quietly so stakeholders do not lose confidence', 'Inspect the impact transparently and renegotiate scope with the Product Owner if the Sprint Goal can still hold', 'Cancel Scrum immediately because compliance work is not Agile', 'Ask Developers to lower quality to fit the new work'),
    correctChoiceId: 'b',
    explanation: 'The strongest response is transparent inspection and scope negotiation. Scrum allows scope clarification as more is learned, but quality should not decrease.',
    whyItMatters: 'Regulatory and compliance risk needs openness, not hidden scope pressure.',
    reference: scrumGuide('The Sprint'),
    tags: ['compliance', 'sprint-scope'],
  },
  {
    id: 'facilitation-coaching-001',
    modes: ['arcade', 'coach'],
    category: 'facilitation-coaching',
    difficulty: 'foundation',
    prompt: 'A retrospective identifies too many improvement ideas. What is the best facilitation move?',
    choices: choices('Pick every idea so no one feels ignored', 'Help the team choose a small number of impactful actions and make ownership visible', 'Skip actions and just thank everyone', 'Let the manager choose privately afterward'),
    correctChoiceId: 'b',
    explanation: 'The strongest facilitation move is to help the team select focused improvements with visible ownership. Too many actions usually means none improve.',
    whyItMatters: 'Team health improves through small completed changes, not a backlog of forgotten retro ideas.',
    tags: ['retrospective', 'continuous-improvement'],
  },
  {
    id: 'facilitation-coaching-002',
    modes: ['arcade', 'coach'],
    category: 'facilitation-coaching',
    difficulty: 'foundation',
    prompt: 'A Scrum Master notices the team waits for them to assign all tasks. What coaching direction best fits Scrum?',
    choices: choices('Assign tasks faster to improve flow', 'Coach the team toward self-management and shared accountability', 'Ask the Product Owner to assign technical tasks', 'Move task assignment to the steering group'),
    correctChoiceId: 'b',
    explanation: 'The Scrum Master serves the team by coaching self-management and cross-functionality, not by becoming a task dispatcher.',
    whyItMatters: 'Self-management supports faster local decisions and stronger ownership of the Sprint Goal.',
    reference: scrumGuide('Scrum Master'),
    tags: ['self-management', 'scrum-master'],
  },
  {
    id: 'facilitation-coaching-003',
    modes: ['arcade', 'coach'],
    category: 'facilitation-coaching',
    difficulty: 'intermediate',
    prompt: 'A quiet engineer raises a concern after a planning meeting, saying they did not feel safe challenging the estimate. What is the best coach response?',
    scenarioContext: 'The concern may affect the Sprint forecast and the team dynamic.',
    choices: choices('Tell them to be braver next time and keep the plan unchanged', 'Create a safer forum to inspect the concern and improve how dissent is invited', 'Ask the manager to correct the engineer privately', 'Ignore the issue because planning is complete'),
    correctChoiceId: 'b',
    explanation: 'The best response addresses both the delivery risk and the team system. Psychological safety and explicit invitation for dissent improve planning quality.',
    whyItMatters: 'Hidden concerns become delivery surprises; good facilitation makes useful disagreement safer.',
    tags: ['psychological-safety', 'planning'],
  },
  {
    id: 'facilitation-coaching-004',
    modes: ['arcade', 'coach'],
    category: 'facilitation-coaching',
    difficulty: 'intermediate',
    prompt: 'A team blames every missed goal on external blockers but never changes its own working agreements. What is the strongest coaching stance?',
    choices: choices('Accept the explanation and end the retrospective early', 'Separate external impediments from team-controlled experiments and choose one change to try', 'Tell the team blockers are not allowed in Agile', 'Move all improvement ownership to the programme manager'),
    correctChoiceId: 'b',
    explanation: 'Good coaching distinguishes external impediments from experiments the team can control. Both may matter, but the team needs agency over its own improvements.',
    whyItMatters: 'A healthy team does not deny constraints; it finds the next useful action within and around them.',
    tags: ['team-health', 'agency'],
  },
  {
    id: 'facilitation-coaching-005',
    modes: ['arcade', 'coach'],
    category: 'facilitation-coaching',
    difficulty: 'intermediate',
    prompt: 'A manager asks to attend every Daily Scrum so they can check individual progress. What should an Agile coach suggest?',
    choices: choices('Make the Daily Scrum a manager status meeting', 'Protect the Developers focus on Sprint Goal progress and offer another transparency mechanism for management', 'Cancel the Daily Scrum to avoid conflict', 'Ask Developers to report only blockers and skip planning'),
    correctChoiceId: 'b',
    explanation: 'The Daily Scrum is for Developers to inspect progress and adapt plans. Management transparency can be supported without changing its purpose into status reporting.',
    whyItMatters: 'Protecting event purpose helps teams self-manage while still giving leaders useful visibility.',
    reference: scrumGuide('Daily Scrum'),
    tags: ['daily-scrum', 'management'],
  },
  {
    id: 'facilitation-coaching-006',
    modes: ['arcade', 'coach'],
    category: 'facilitation-coaching',
    difficulty: 'advanced',
    prompt: 'An Agile Coach is asked to "install Agile" by enforcing one process across very different teams. What is the strongest response?',
    scenarioContext: 'Some teams use Scrum, others use flow-based delivery, and their constraints differ.',
    choices: choices('Mandate one ceremony set for every team', 'Coach around principles, transparency and outcomes while letting practices fit context', 'Remove all process language and rely on heroics', 'Rate teams only by compliance with the chosen template'),
    correctChoiceId: 'b',
    explanation: 'Agile coaching should connect principles, transparency and outcomes to context. Practices can vary when they preserve the intent and make delivery healthier.',
    whyItMatters: 'Process compliance can look neat while reducing agility; coaching should improve the system, not just standardize vocabulary.',
    tags: ['agile-coaching', 'context'],
  },
];

export const getCategoryLabel = (categoryId) =>
  QUIZ_CATEGORIES.find((category) => category.id === categoryId)?.label ?? categoryId;
